### ISSUE TITLE
Some question with home-manager

### ISSUE THREAD

**Issue by yfaimisaka** [Misterio77/nix-config#10]
I am nearly new one to nixos, after reading your config I learned a lot, and here comes some question.

https://github.com/Misterio77/nix-config/blob/25b80e0a69e069a0eafb89a649eeaf8a2c5e93d6/hosts/common/users/misterio/default.nix#L37
Here,  you used  `home-manager ` under hosts directory(or say, in `nixosConfiguration` use?), I did the same way, while running `nixos-rebuild switch --flake . ` got some error like this:
```
error: The option `home-manager' does not exist. Definition values:
       - In `/nix/store/g57dw7gngchrksv935nhziyl45nj0hwf-source/hosts/common/users/aimi':
           {
             users = {
               aimi = <function, args: {inputs, pkgs}>;
             };
           }
 ```
and find something in nixos wiki like this `To use it inside nixosConfigurations in a Flake, put home-manager in your inputs and in your configuration modules import home-manager.nixosModules.home-manager, then you can use it as above. `
It's in [here](https://nixos.wiki/wiki/Home_Manager) . But I did'nt see any thing like `home-manager.nixosModules.home-manager` in your config, did you use other method or I had some misunderstanding with nixos wiki's word?

Thanks

**Comment by yfaimisaka** [comment]
I saw this in here: https://github.com/Misterio77/nix-config/blob/25b80e0a69e069a0eafb89a649eeaf8a2c5e93d6/hosts/common/global/default.nix#L6
I'm sorry to be too fool. :)

**Comment by Misterio77** [comment]
Hey, sorry, I didn't see this earlier. Glad you got it working! Let me know if there's anything I can help you with :)
