### ISSUE TITLE
QUESTION: how to add an remote nixpkgs-overlay

### ISSUE THREAD

**Issue by tom-tubeless** [Misterio77/nix-config#12]
I have a flake-setup similar to yours (it's shamelessly boroughed actually) and can't figure out, how to add an overlay like [Neorg overlay for Nixpkgs](https://github.com/nvim-neorg/nixpkgs-neorg-overlay). Maybe you can shed some light on my ignorance.

Thank you very much in advance.

**Comment by Misterio77** [comment]
Hello!

It's actually simpler than it sounds. Make sure you're passing `inputs` (e.g. [by using specialArgs on your flake](https://github.com/Misterio77/nix-config/blob/4da13f2309ddf8da729d46faa7fec9f182362846/flake.nix#L80)), and set `nixpkgs.overlays`. You can do this in any file that is part of your NixOS (or home-manager) configuration. [Here's an example on my own config](https://github.com/Misterio77/nix-config/blob/4da13f2309ddf8da729d46faa7fec9f182362846/hosts/alcyone/services/firefly.nix#L7).

Here's a simple example on nix-starter-config: https://github.com/Misterio77/nix-starter-configs/blob/main/minimal/home-manager/home.nix#L18

For neorg it would be something like:
```nix
{ inputs, ... }: {
  nixpkgs.overlays = [ inputs.neorg-overlay.overlays.default ];
}
```

For neorg, you will probably want to do it on your home-manager configuration. If you're using home-manager as a NixOS module (i.e. not standalone), setting it anywhere on your NixOS configuration will also work, as long as you have `home-manager.useGlobalPkgs = true`.

**Comment by Misterio77** [comment]
Please let me know if something was confusing or if you need any other help! I will be happy to help :)

**Comment by tom-tubeless** [comment]
Thank you for the kind and complete answer. When I read it now, I actually do not know at which point I had difficulties. Maybe I was overthinking. Again, thank you very much, it works now as expected.
