### ISSUE TITLE
Ci/Cd?

### ISSUE THREAD

**Issue by Mateiadrielrafael** [Misterio77/nix-config#16]
I see you are using hydra. I'm yet to set it up myself, but as far as I can understand it let's you build nix stuff automatically. Does your setup have a way to automatically deploy your website and other things? (or do you manually call the deploy script whenever you feel like it?)

**Comment by Misterio77** [comment]
I do have CD! It's a pull-based deployment, that means the machines auto-upgrade themselves from hydra.

I basically [have my hydra run](https://github.com/Misterio77/nix-config/blob/main/hosts/celaeno/services/hydra/default.nix#L41) [a script](https://github.com/Misterio77/nix-config/blob/main/hosts/celaeno/services/hydra/lib/release-host-branch.nix) that pushes release branches corresponding to each host's name (e.g. `release-atlas`).

[I then point `system.autoUpgrade.flake` to the correct branch](https://github.com/Misterio77/nix-config/blob/main/hosts/common/global/auto-upgrade.nix), for example:
```nix
{ config, ... }: {
  system.autoUpgrade = {
    enable = true;
    flake = "github:you/nix-config/release-${config.networking.hostName}";
  };
}
```

And there you have it, pull based deployment. I think someone should add something like `system.autoUpgrade.hydraJob` though, would make things a lot easier.
