### ISSUE TITLE
Home-Manager not working as anticipated

### ISSUE THREAD

**Issue by lutzgo** [Misterio77/nix-config#2]
First of all: Great work! Your starter-config helped me to understand nix-flake configuration a little more and your nix-config checked all the boxes for me: encrypted btrfs, impermanence, multiple users and host-machines ans everything in one flake-file.

Thanks to your nix-config I have a running NixOS although I am struggling with the home-manager (not for the first time). I can build and switch with `home-manager switch --flake $user@$host` but `home-manager packages` gives me nothing. I remember that I had problems with home-manager before (with a much simpler config) getting sway to work. Do you have any clues, what might be the problem? I basically edited your configuration to my needs.

Thank you in advance

Lutz

**Comment by Misterio77** [comment]
Thank you for your kind words! I'm really glad I could help out fellow nixers with my configs :D

Hmm, maybe you might have some kind of issue with the new `nix profile`? home-manager isn't very compatible with it.

I think you can switch back to `nix-env` by using `rm /nix/var/nix/profiles/per-user/$USER/profile`.

Let me know if it works!

**Comment by lutzgo** [comment]
Thank you for the fast reply.

Removing of the per-user-profile had the effect, that the home-manager-configuration was build completely (my hopes where getting up). But after completion there is still nothing to be found with `home-manager packages`. I would really like to use home-manger especially for sway and the cli-config.

If it helps, my configuration is located at [nix-config](https://github.com/lutzgo/nix-config). Feel free to comment on my humble copy of your configuration (at the time I am using Gnome in the host-config as I have to get some things working).

Best Regards

Lutz

**Comment by Misterio77** [comment]
Hey!

I'm hmm... Kinda out of ideas here. You're running something like (of course, with your own user and host) `home-manager switch --flake .#misterio@atlas`? The `.` is very important, as it tells home-manager to use the repository you're in, not the default path (which is `.config/nixpkgs` IIRC)

**Comment by lutzgo** [comment]
Thank you for your patience. The `home-manager switch -b backup --flake .#lgo@flores` was build as expected (I have to use `-b backup` because of the existing firefox-profile. After the build I got:

```
Starting Home Manager activation
Activating checkFilesChanged
Activating checkLinkTargets
Activating unmountPersistentStoragePaths
Activating createAndMountPersistentStoragePaths
fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option
```

The same goes for the `nix build`-approach.

**Comment by Misterio77** [comment]
Yeah, this is an error from impermanence, it's kinda of a pain they don't tell which mountpoint is conflicted haha.

Okay hm you can try commenting out every `home.persistence` block (or set `persistent = false` on your flake), check if it works, and then uncomment half of then and so on, until you know what is conflicting.

**Comment by lutzgo** [comment]
Hey, that was a partial success. home-manager is working with persitance completly disabled. As soon as I enable it (wether or not something else is commented out or not) I get the described error.

Thank you so far. My system is usable now :)

**Comment by Misterio77** [comment]
Glad you got it working :)

Impermanence sure is a tough nut to crack. Enabling one at a time should help!

**Comment by badele** [comment]
> Thank you for your patience. The `home-manager switch -b backup --flake .#lgo@flores` was build as expected (I have to use `-b backup` because of the existing firefox-profile. After the build I got:
> 
> ```
> Starting Home Manager activation
> Activating checkFilesChanged
> Activating checkLinkTargets
> Activating unmountPersistentStoragePaths
> Activating createAndMountPersistentStoragePaths
> fuse: mountpoint is not empty
> fuse: if you are sure this is safe, use the 'nonempty' mount option
> ```
> 
> The same goes for the `nix build`-approach.

Indeed, it's a bit annoying, there is no debugging option in the home-manager mode.

I think that during the home-manager switch phase, if an application writes to one of the impermanence mount folders, that impermanence (fuse) cannot mount the whole impermanence.

It's a shame, because the idea was good, but too restrictive, I deactivated it
