### ISSUE TITLE
Question: How to deploy on Raspberry Pi 4

### ISSUE THREAD

**Issue by SolidRhino** [Misterio77/nix-config#21]
How can you deploy this on a Raspberry Pi 4? Because the image for the Raspberry Pi 4 is also the installation medium and isn't using BTRFS.

**Comment by hellst0rm** [comment]
my suggestion for you is to todo as I am doing it by following these blogs:

- [https://carjorvaz.com/posts/nixos-on-raspberry-pi-4-with-uefi-and-zfs/](Installing NixOS on the Raspberry Pi 4 with UEFI and ZFS)
- [https://grahamc.com/blog/erase-your-darlings/](Erase your darlings)
- and this nixos starter config template

**Comment by Misterio77** [comment]
Hey,

I don't really remember how I did it lol, but IIRC: I first installed it with ext4, then re-configured it to use btrfs, ran `nixos-rebuild boot`, formatted (with a PC) the SD card as btrfs, and inserted it back. It should do the trick!

nixos-anywhere is also a good option for that, if your rasp has enough ram for it.
