### ISSUE TITLE
Firefox add-ons issue

### ISSUE THREAD

**Issue by taha-yassine** [Misterio77/nix-config#25]
Hi,
First of all thanks a lot for your work, it was the most helpful resource in my NixOS journey.
I'm trying to add Firefox add-ons to my setup through hm. I use your Standard config. Inspired by this repo, I added
```nix
firefox-addons = {
  url = "gitlab:rycee/nur-expressions?dir=pkgs/firefox-addons";
  inputs.nixpkgs.follows = "nixpkgs";
};
```
to the inputs of my `flake.nix` and
```nix
extensions = with pkgs.inputs.firefox-addons; [
  ublock-origin
  bitwarden
];
```
to my Firefox entry in `home.nix`.
When I run the hm switch command I get this error:
```
error: attribute 'inputs' missing
```
Is there something wrong I'm doing?
Thanks!

**Comment by eyduh** [comment]
had missed to look through and add the appropriate home-manager modules. nvm x

**Comment by t-chab** [comment]
Hello, as @taha-yassine said, thanks a lot for your inspiring flake repo. 

@taha-yassine : I get the same error as you when I try to add firefox addons to my setup. I'll tell you if I find a workaround or a solution.

**Comment by taha-yassine** [comment]
> Hello, as @taha-yassine said, thanks a lot for your inspiring flake repo.
> 
> @taha-yassine : I got the same error as you when I first tried to add firefox addons to my setup.
> 
> I still do not figure out why (I'm still a huge nix noob 😅 ) but after adding [this code snippet to my setup](https://github.com/Misterio77/nix-config/blob/main/overlays/default.nix#L8-L20) it seems to fix the issue.

Thanks a lot for your answer. I asked about this same issue in the NixOS forums and someone suggested a fix similar to what you are suggesting: https://discourse.nixos.org/t/firefox-extensions-with-home-manager/34108
