### ISSUE TITLE
btrfs-optin-persistence issue

### ISSUE THREAD

**Issue by dechnik** [Misterio77/nix-config#9]
I really like your work on this config setup. Trying to implement this btrfs-optin-persistence solution in my configs, but I'm having troubles with proper setup. Does it require special btrfs/subvolumes configuration? After enabling this feature my system won't boot.

**Comment by luxus** [comment]
i'm not the author, but did you change the `LABEL` of your partition to your hostname?

**Comment by dechnik** [comment]
ok found issue with my setup, there was no root-blank subvolume, now it is working ;)
